pages:
  stage: deploy
  script:
    - mkdir public
    - cp index.html public/
    - cp -r "architecture information" public/
    - cp -r roots public/
    - cp -r script public/
    - cp -r style public/
  artifacts:
    paths:
      - public
  only:
    - main