pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir public
    - cp index.html public/
    - cp -r script public/
    - cp -r style public/
    - cp -r roots public/
    - cp -r architecture_information public/ || true
  artifacts:
    paths:
      - public
  only:
    - main